apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: gcr.io/manage-261115/petclinic
        ports:
        - containerPort: 8080
---          
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: petclinic
---    
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
spec:
  rules:
  - host: petclinic.mc1985.net
    http:
      paths:
      - path: /*
        backend:
          serviceName: petclinic
          servicePort: 80
